### ISSUE TITLE
Add submitted yaml to the yaml validator results for comparison

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#906]
On the metadata validator results page, can you please add the original submitted yaml for comparison against the interpreted JSON? That way it can at least be quickly compared with the interpreted JSON to see if it matches. In this case the `division` is silently dropped because we don't support divisions, and division should just be included with the department if the division needs to be credited in the metadata. Ideally we should also highlight uninterpreted yaml, but I know that will be harder to do.

```yaml
contributor:
 - name: University of Testing
   department: Test Department
   division: Test Division
   city: Test
   state: TE
   country: US
```

![image](https://user-images.githubusercontent.com/8573609/122434075-65652380-cf5c-11eb-8868-235180e82a00.png)
